server:
  port: 8087
spring:
  jpa:
    properties:
      hibernate.dialect:
        org.hibernate.dialect.MySQL5Dialect
---
spring:
  profiles:
    active: cloud
  datasource:
    url: jdbc:mysql://localhost:3306/ad_f33ba6ada231ff9?useSSL=false&user=root&password=root
---  
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/ad_f33ba6ada231ff9?useSSL=false&user=root&password=root
   
eureka:
  instance:
    non-secure-port: 80
    hostname: ${vcap.application.uris[0]:localhost:8761}
  
  client:
    service-url:
      defaultZone: ${vcap.services.eureka.credentials.url:http://localhost:8761/eureka/}