server:
  port: 8082
  max-http-header-size: 2012333
---
server:
  context-path: /
---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  profiles: local, cloud
  datasource:
    url: ${cloud.services.postgres-sql.connection.jdbcUrl:jdbc:mysql://localhost:3306/ad_f33ba6ada231ff9?useSSL=false&user=root&password=root}
---
 eureka:
  instance:
    non-secure-port-enabled: false
    secure-port-enabled: true
    hostname: ${vcap.application.uris[0]:localhost:8761}
    status-page-url: https://${eureka.instance.hostname}/info
    health-check-url: https://${eureka.instance.hostname}/health
    home-page-url: https://${eureka.instance.hostname}/
    secure-virtual-host-name: https://${vcap.application.uris[0]:localhost:8761}
  
  client:
    service-url:
      defaultZone: ${vcap.services.eureka.credentials.url:http://localhost:8761/eureka/}          
      
---
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

---
 spring:
  jpa:
    properties:
      hibernate.dialect:
        org.hibernate.dialect.PostgreSQLDialect 
  http:
    multipart:
      max-request-size: 10Mb
      